[11.0][mig] privacy consent
OCA/data-protection pull request #27
Opened 2019-03-25 08:10 UTC by fkantelberg

Hello everyone,
this is the port of the privacy_consent module. Due to changes in v11 _ir.actions.server_ odoo run into an infinite loop which required the changes in the xml.

2019-07-04 10:15 UTC, chienandalu requested changes
Thanks @fkantelberg Can you get the latest commits fixing some issues in `10.0`?: https://github.com/OCA/data-protection/commits/10.0/privacy_consent

@Yajo Can you take a look on this?

2019-07-04 11:46 UTC, yajo requested changes
It looks good, overall. 2 requirements, though:

1. Include latest commits from branch 10.0. They are very important fixes.
1. Squash your migration commits in 1.

Also a suggestion to make it look better:

2019-07-04 11:46 UTC, Yajo commented on privacy_consent/data/ir_actions_server.xml
> +        <field name="code">for record in records:
```suggestion
        <field name="code">records.mapped("partner_id").write({'opt_out': not record.accepted})</field>
```

2019-07-04 11:46 UTC, Yajo commented on privacy_consent/data/ir_actions_server.xml
> +            record.partner_id.write({'opt_out': not record.accepted})</field>
```suggestion
```

2019-07-04 12:47 UTC, fkantelberg commented
@Yajo @chienandalu Thank you for your feedback. I did your wanted changes.

2019-07-05 05:53 UTC, chienandalu requested changes
Thanks @fkantelberg 

There's a little issue in the `privacy` module form view of the activity with the domain, as the widget used should be `domain` and not `char_domain` which is a deprecated key. It's out of the scope for this module, but if want to make the fix I note it here :)

I little remark on your code below:

2019-07-05 05:53 UTC, chienandalu commented on privacy_consent/data/ir_cron.xml
> +        <field name="code">model._cron_new_consents()</field>
You've missed the `state` key here
```suggestion
        <field name="state">code</field>
        <field name="code">model._cron_new_consents()</field>
```

2019-07-05 06:18 UTC, fkantelberg commented
@chienandalu I added the state and made a second commit for the view change.

2019-07-05 07:21 UTC, yajo requested changes

2019-07-05 07:21 UTC, Yajo commented on privacy_consent/views/res_partner.xml
> +                <!-- TODO Change icon to fa-handshake-o in Odoo 11 -->
Let's do this now.

```suggestion
```

2019-07-05 07:21 UTC, Yajo commented on privacy_consent/views/res_partner.xml
> +                    icon="fa-gavel"
```suggestion
                    icon="fa-handshake-o"
```

2019-07-05 07:21 UTC, Yajo commented on privacy_consent/views/privacy_activity.xml
> +                <!-- TODO Change icon to fa-handshake-o in Odoo 11 -->
Let's obey this comment.
```suggestion
```

2019-07-05 07:21 UTC, Yajo commented on privacy_consent/views/privacy_activity.xml
> +                    icon="fa-gavel"
```suggestion
                    icon="fa-handshake-o"
```

2019-07-05 07:40 UTC, fkantelberg commented
@Yajo I haven't seen that comment in my tests but thanks for noticing. I changed the icons

2019-07-05 09:08 UTC, yajo approved these changes
/ocabot merge

2019-07-05 09:08 UTC, Yajo commented
/ocabot merge

2019-07-05 09:26 UTC, merged