[MIG] privacy_consent: Migrate to v12
OCA/data-protection pull request #33
Opened 2019-07-08 11:49 UTC by Yajo

- Partner's `opt_out` no longer exists. Using `mail.blacklist` now.
- Tests updated to support that change.
- Test workarounds removed.
- Duplicated-field-name-in-model warning removed.

@Tecnativa

2019-07-08 17:45 UTC, pedrobaeza approved these changes

2019-07-08 17:46 UTC, pedrobaeza commented
Please fix little flake8 error:
```
privacy_consent/tests/test_consent.py:4:1: F401 'contextlib.contextmanager' imported but unused
```

2019-07-09 07:54 UTC, Yajo commented
Fixed.

2019-07-09 15:23 UTC, Tardo requested changes

2019-07-09 15:23 UTC, Tardo commented on privacy_consent/models/mail_template.py
> +        links = [u"//a[@href='/privacy/consent/{}/']".format(action)
Python 3 works with unicode strings by default...
https://www.python.org/dev/peps/pep-3120/ says...
```With Python 3, all strings will be Unicode strings, so the original encoding of the source will have no impact at run-time.```
Another related PEP: https://www.python.org/dev/peps/pep-0414/
```

2019-07-09 15:23 UTC, Tardo commented on privacy_consent/models/privacy_activity.py
> +                consents |= consents.create({
Here perhaps can use create (multi style)

2019-07-10 08:23 UTC, Yajo commented
Thanks @Tardo, all  fixed.

2019-07-15 15:24 UTC, Tardo requested changes

2019-07-15 15:24 UTC, Tardo commented on privacy_consent/models/privacy_consent.py
> +        result = super(PrivacyConsent, self).write(vals)
```suggestion
        result = super().write(vals)
```

2019-07-15 15:24 UTC, Tardo commented on privacy_consent/models/privacy_consent.py
> +        result = super(PrivacyConsent, self) \
```suggestion
        result = super() \
```

2019-07-16 09:25 UTC, Tardo approved these changes
:+1: code review

2019-07-16 09:59 UTC, pedrobaeza commented
/ocabot merge

2019-07-16 11:01 UTC, merged